package com.company.speedment.test.sql696688.db0.sql696688.user.impl;

import com.company.speedment.test.sql696688.db0.sql696688.user.User;
import com.speedment.Speedment;
import com.speedment.internal.core.code.AbstractBaseEntity;
import java.util.Objects;
import java.util.StringJoiner;
import javax.annotation.Generated;

/**
 * An implementation representing an entity (for example, a row) in the Table
 * 'sql696688.db0.sql696688.user'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public final class UserImpl extends AbstractBaseEntity<User> implements User {
    
    private Long id;
    private String name;
    private Integer age;
    
    UserImpl(Speedment speedment) {
        super(speedment);
    }
    
    public UserImpl(Speedment speedment, final User user) {
        super(speedment);
        setId(user.getId());
        setName(user.getName());
        setAge(user.getAge());
    }
    
    @Override
    public Long getId() {
        return id;
    }
    
    @Override
    public String getName() {
        return name;
    }
    
    @Override
    public Integer getAge() {
        return age;
    }
    
    @Override
    public final UserImpl setId(Long id) {
        this.id = id;
        return this;
    }
    
    @Override
    public final UserImpl setName(String name) {
        this.name = name;
        return this;
    }
    
    @Override
    public final UserImpl setAge(Integer age) {
        this.age = age;
        return this;
    }
    
    @Override
    public User copy() {
        return new UserImpl(getSpeedment_(), this);
    }
    
    @Override
    public String toString() {
        final StringJoiner sj = new StringJoiner(", ", "{ ", " }");
        sj.add("id = "+Objects.toString(getId()));
        sj.add("name = "+Objects.toString(getName()));
        sj.add("age = "+Objects.toString(getAge()));
        return "UserImpl "+sj.toString();
    }
    
    @Override
    public boolean equals(Object that) {
        if (this == that) { return true; }
        if (!(that instanceof User)) { return false; }
        @SuppressWarnings("unchecked")
        final User thatUser = (User)that;
        if (!Objects.equals(this.getId(), thatUser.getId())) {return false; }
        if (!Objects.equals(this.getName(), thatUser.getName())) {return false; }
        if (!Objects.equals(this.getAge(), thatUser.getAge())) {return false; }
        return true;
    }
    
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(getId());
        hash = 31 * hash + Objects.hashCode(getName());
        hash = 31 * hash + Objects.hashCode(getAge());
        return hash;
    }
    
    @Override
    public Class<User> getEntityClass_() {
        return User.class;
    }
}